### PR TITLE
Analytics: Fix outlink tracking

### PR DESCRIPTION
**Pull request by robredpath**

### CODE REVIEW

**Comment by robredpath** [comment]
Fixes the issue described in https://opendataservices.plan.io/issues/34546

**Comment by michaelwood** [comment]
@robredpath double checking - From reading the docs all this will mean is that links from grantnav.threesixtygiving.org to (for example  insights.threesixtygiving.org) will be counted as outlinks.

Given that we're seeing flat line on the graph in the screenshot provided I'm wondering why there are none that don't match that domain e.g. ones in the footer, twitter, github , creative commons etc. Or is it just probable that no one has clicked an external link in that time period. 

ref: https://developer.matomo.org/guides/tracking-javascript-guide#outlink-tracking-exclusions

**Comment by michaelwood** [comment]
> @robredpath double checking - From reading the docs all this will mean is that links from grantnav.threesixtygiving.org to (for example insights.threesixtygiving.org) will be counted as outlinks.
> 
> Given that we're seeing flat line on the graph in the screenshot provided I'm wondering why there are none that don't match that domain e.g. ones in the footer, twitter, github , creative commons etc. Or is it just probable that no one has clicked an external link in that time period.
> 

Clarification received that the graph in the screenshot was for a particular outlink domain and not showing the outlinks occurring on  grantnav.threesixtygiving.org

**Comment by michaelwood** [comment]
Looks good. I will keep this PR open to track deploys across the products

**Review by michaelwood — APPROVED** [review]

**Pull request merged**
